services:
  mysql:
    image: mysql:8.3
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306 # < Probably a good idea to change to expose in production
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
      
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 80
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - SQL_HOST=mysql
      - SQL_USER=root
      - SQL_PWD=password
    expose:
      - 80
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']

volumes:
  mysql-data: